<?php

namespace Database\Seeders;

use App\Models\Asset;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus semua data aset yang lama dengan disable foreign key constraints
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Asset::truncate();
        \DB::table('depreciation_histories')->truncate(); // Hapus juga history terkait
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $assets = [
            // ELEKTRONIK - Depreciation
            [
                'name' => 'Laptop Dell Latitude 5420',
                'room_name' => 'Ruang IT',
                'location' => 'Gedung A',
                'floor' => 'Lantai 3',
                'asset_code' => 'AKT-001',
                'unit_code' => 'SAT-001',
                'received_date' => '2023-01-15',
                'purchase_price' => 15000000,
                'useful_life' => 5,
                'salvage_value' => 2000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Dell',
                'serial_number' => 'DL2023001',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Laptop untuk staff IT',
                'user_assigned' => 'Ahmad Hidayat',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 15000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Printer HP LaserJet Pro',
                'room_name' => 'Ruang Administrasi',
                'location' => 'Gedung A',
                'floor' => 'Lantai 2',
                'asset_code' => 'AKT-002',
                'unit_code' => 'SAT-002',
                'received_date' => '2022-06-10',
                'purchase_price' => 5500000,
                'useful_life' => 4,
                'salvage_value' => 500000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 20.0,
                'brand' => 'HP',
                'serial_number' => 'HP2022456',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Printer untuk cetak dokumen',
                'user_assigned' => 'Siti Nurhaliza',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 5500000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Proyektor Epson EB-X41',
                'room_name' => 'Ruang Rapat Utama',
                'location' => 'Gedung B',
                'floor' => 'Lantai 4',
                'asset_code' => 'AKT-003',
                'unit_code' => 'SAT-003',
                'received_date' => '2023-03-20',
                'purchase_price' => 8000000,
                'useful_life' => 6,
                'salvage_value' => 1000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Epson',
                'serial_number' => 'EP2023789',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Proyektor untuk presentasi',
                'user_assigned' => 'Budi Santoso',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 8000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'AC Panasonic 2 PK',
                'room_name' => 'Ruang Direktur',
                'location' => 'Gedung A',
                'floor' => 'Lantai 5',
                'asset_code' => 'AKT-004',
                'unit_code' => 'SAT-004',
                'received_date' => '2021-08-15',
                'purchase_price' => 6500000,
                'useful_life' => 8,
                'salvage_value' => 800000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 15.0,
                'brand' => 'Panasonic',
                'serial_number' => 'PN2021345',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'AC ruang direktur',
                'user_assigned' => 'Direktur Utama',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 6500000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Server Dell PowerEdge R740',
                'room_name' => 'Ruang Server',
                'location' => 'Gedung A',
                'floor' => 'Lantai 1',
                'asset_code' => 'AKT-005',
                'unit_code' => 'SAT-005',
                'received_date' => '2022-12-01',
                'purchase_price' => 85000000,
                'useful_life' => 7,
                'salvage_value' => 10000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Dell',
                'serial_number' => 'DL2022SRV',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Server utama perusahaan',
                'user_assigned' => 'IT Department',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 85000000,
                'last_depreciation_date' => null,
            ],

            // FURNITURE - Depreciation
            [
                'name' => 'Meja Kantor Kayu Jati',
                'room_name' => 'Ruang Manager',
                'location' => 'Gedung B',
                'floor' => 'Lantai 3',
                'asset_code' => 'AKT-006',
                'unit_code' => 'SAT-006',
                'received_date' => '2022-04-10',
                'purchase_price' => 7500000,
                'useful_life' => 10,
                'salvage_value' => 1500000,
                'type' => 'Furniture',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 10.0,
                'brand' => 'Olympic',
                'serial_number' => 'OL2022MJ',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Meja kerja manager',
                'user_assigned' => 'Rina Wijaya',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 7500000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Kursi Ergonomis Ergo Chair',
                'room_name' => 'Ruang Staff',
                'location' => 'Gedung A',
                'floor' => 'Lantai 2',
                'asset_code' => 'AKT-007',
                'unit_code' => 'SAT-007',
                'received_date' => '2023-05-20',
                'purchase_price' => 3500000,
                'useful_life' => 5,
                'salvage_value' => 500000,
                'type' => 'Furniture',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'ErgoChair',
                'serial_number' => 'EC2023KR',
                'quantity' => 10,
                'status' => 'Baik',
                'description' => 'Kursi staff kantor',
                'user_assigned' => 'Staff Umum',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 3500000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Lemari Arsip Besi 2 Pintu',
                'room_name' => 'Ruang Arsip',
                'location' => 'Gedung A',
                'floor' => 'Lantai 1',
                'asset_code' => 'AKT-008',
                'unit_code' => 'SAT-008',
                'received_date' => '2021-09-15',
                'purchase_price' => 4200000,
                'useful_life' => 12,
                'salvage_value' => 800000,
                'type' => 'Furniture',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 8.0,
                'brand' => 'Lion',
                'serial_number' => 'LN2021AR',
                'quantity' => 5,
                'status' => 'Baik',
                'description' => 'Lemari penyimpanan dokumen',
                'user_assigned' => 'Bagian Arsip',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 4200000,
                'last_depreciation_date' => null,
            ],

            // KENDARAAN - Depreciation dengan custom rate
            [
                'name' => 'Mobil Toyota Avanza 1.3 G',
                'room_name' => 'Parkir Gedung',
                'location' => 'Basement',
                'floor' => 'B1',
                'asset_code' => 'AKT-009',
                'unit_code' => 'SAT-009',
                'received_date' => '2021-11-20',
                'purchase_price' => 225000000,
                'useful_life' => 8,
                'salvage_value' => 50000000,
                'type' => 'Kendaraan',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 25.0,
                'brand' => 'Toyota',
                'serial_number' => 'TY2021AVZ',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Mobil operasional',
                'user_assigned' => 'Pool Kendaraan',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 225000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Motor Honda Vario 150',
                'room_name' => 'Parkir Motor',
                'location' => 'Gedung A',
                'floor' => 'Basement',
                'asset_code' => 'AKT-010',
                'unit_code' => 'SAT-010',
                'received_date' => '2023-02-10',
                'purchase_price' => 25000000,
                'useful_life' => 6,
                'salvage_value' => 5000000,
                'type' => 'Kendaraan',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 20.0,
                'brand' => 'Honda',
                'serial_number' => 'HD2023VR',
                'quantity' => 2,
                'status' => 'Baik',
                'description' => 'Motor dinas',
                'user_assigned' => 'Kurir',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 25000000,
                'last_depreciation_date' => null,
            ],

            // TANAH - Appreciation
            [
                'name' => 'Tanah Kavling Bogor',
                'room_name' => 'Area Outdoor',
                'location' => 'Bogor',
                'floor' => 'Ground',
                'asset_code' => 'AKT-011',
                'unit_code' => 'SAT-011',
                'received_date' => '2020-06-15',
                'purchase_price' => 500000000,
                'useful_life' => 50,
                'salvage_value' => 0,
                'type' => 'Tanah',
                'depreciation_type' => 'appreciation',
                'custom_depreciation_rate' => 5.0,
                'brand' => '-',
                'serial_number' => 'TNH2020BGR',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Tanah investasi 500m2',
                'user_assigned' => 'Perusahaan',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 500000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Tanah Kampus Utama',
                'room_name' => 'Area Kampus',
                'location' => 'Jakarta Pusat',
                'floor' => 'Ground',
                'asset_code' => 'AKT-012',
                'unit_code' => 'SAT-012',
                'received_date' => '2015-03-01',
                'purchase_price' => 2000000000,
                'useful_life' => 50,
                'salvage_value' => 0,
                'type' => 'Tanah',
                'depreciation_type' => 'appreciation',
                'custom_depreciation_rate' => 7.0,
                'brand' => '-',
                'serial_number' => 'TNH2015KMP',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Tanah lokasi kampus 2000m2',
                'user_assigned' => 'Universitas',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 2000000000,
                'last_depreciation_date' => null,
            ],

            // BANGUNAN - Appreciation
            [
                'name' => 'Gedung Kuliah 5 Lantai',
                'room_name' => 'Gedung Utama',
                'location' => 'Jakarta Pusat',
                'floor' => '1-5',
                'asset_code' => 'AKT-013',
                'unit_code' => 'SAT-013',
                'received_date' => '2018-08-20',
                'purchase_price' => 15000000000,
                'useful_life' => 40,
                'salvage_value' => 0,
                'type' => 'Bangunan',
                'depreciation_type' => 'appreciation',
                'custom_depreciation_rate' => 3.0,
                'brand' => '-',
                'serial_number' => 'BNG2018GD5',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Gedung perkuliahan utama',
                'user_assigned' => 'Universitas',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 15000000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Gedung Laboratorium',
                'room_name' => 'Lab Complex',
                'location' => 'Jakarta Pusat',
                'floor' => '1-3',
                'asset_code' => 'AKT-014',
                'unit_code' => 'SAT-014',
                'received_date' => '2020-12-10',
                'purchase_price' => 8000000000,
                'useful_life' => 35,
                'salvage_value' => 0,
                'type' => 'Bangunan',
                'depreciation_type' => 'appreciation',
                'custom_depreciation_rate' => null,
                'brand' => '-',
                'serial_number' => 'BNG2020LAB',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Gedung laboratorium',
                'user_assigned' => 'Fakultas Teknik',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 8000000000,
                'last_depreciation_date' => null,
            ],

            // ELEKTRONIK LAINNYA
            [
                'name' => 'Scanner Canon DR-C225',
                'room_name' => 'Ruang Dokumentasi',
                'location' => 'Gedung B',
                'floor' => 'Lantai 2',
                'asset_code' => 'AKT-015',
                'unit_code' => 'SAT-015',
                'received_date' => '2023-07-05',
                'purchase_price' => 12000000,
                'useful_life' => 5,
                'salvage_value' => 1500000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 18.0,
                'brand' => 'Canon',
                'serial_number' => 'CN2023SCN',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Scanner dokumen',
                'user_assigned' => 'Bagian Dokumentasi',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 12000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'CCTV Hikvision 16 Channel',
                'room_name' => 'Ruang Security',
                'location' => 'Gedung A',
                'floor' => 'Lantai 1',
                'asset_code' => 'AKT-016',
                'unit_code' => 'SAT-016',
                'received_date' => '2022-10-15',
                'purchase_price' => 35000000,
                'useful_life' => 8,
                'salvage_value' => 3000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Hikvision',
                'serial_number' => 'HK2022CTV',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Sistem CCTV gedung',
                'user_assigned' => 'Security',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 35000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Komputer Desktop HP Elite',
                'room_name' => 'Ruang Staff Keuangan',
                'location' => 'Gedung A',
                'floor' => 'Lantai 4',
                'asset_code' => 'AKT-017',
                'unit_code' => 'SAT-017',
                'received_date' => '2023-01-10',
                'purchase_price' => 18000000,
                'useful_life' => 5,
                'salvage_value' => 2000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 22.0,
                'brand' => 'HP',
                'serial_number' => 'HP2023DSK',
                'quantity' => 5,
                'status' => 'Baik',
                'description' => 'PC desktop staff keuangan',
                'user_assigned' => 'Bagian Keuangan',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 18000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Mesin Fotocopy Xerox WorkCentre',
                'room_name' => 'Ruang Fotocopy',
                'location' => 'Gedung B',
                'floor' => 'Lantai 1',
                'asset_code' => 'AKT-018',
                'unit_code' => 'SAT-018',
                'received_date' => '2022-03-25',
                'purchase_price' => 45000000,
                'useful_life' => 6,
                'salvage_value' => 5000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Xerox',
                'serial_number' => 'XR2022FCY',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Mesin fotocopy multifungsi',
                'user_assigned' => 'Umum',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 45000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'UPS APC 10KVA',
                'room_name' => 'Ruang Server',
                'location' => 'Gedung A',
                'floor' => 'Lantai 1',
                'asset_code' => 'AKT-019',
                'unit_code' => 'SAT-019',
                'received_date' => '2022-11-30',
                'purchase_price' => 28000000,
                'useful_life' => 7,
                'salvage_value' => 3000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 16.0,
                'brand' => 'APC',
                'serial_number' => 'APC2022UPS',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'UPS untuk server',
                'user_assigned' => 'IT Department',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 28000000,
                'last_depreciation_date' => null,
            ],

            // FURNITURE TAMBAHAN
            [
                'name' => 'Sofa Ruang Tamu Kulit',
                'room_name' => 'Ruang Tamu Direktur',
                'location' => 'Gedung A',
                'floor' => 'Lantai 5',
                'asset_code' => 'AKT-020',
                'unit_code' => 'SAT-020',
                'received_date' => '2023-04-15',
                'purchase_price' => 25000000,
                'useful_life' => 10,
                'salvage_value' => 5000000,
                'type' => 'Furniture',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 12.0,
                'brand' => 'Atria',
                'serial_number' => 'AT2023SFA',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Sofa set ruang tamu',
                'user_assigned' => 'Direktur',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 25000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Meja Rapat Oval 12 Orang',
                'room_name' => 'Ruang Rapat Besar',
                'location' => 'Gedung B',
                'floor' => 'Lantai 5',
                'asset_code' => 'AKT-021',
                'unit_code' => 'SAT-021',
                'received_date' => '2022-05-20',
                'purchase_price' => 18000000,
                'useful_life' => 12,
                'salvage_value' => 3000000,
                'type' => 'Furniture',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Vivere',
                'serial_number' => 'VV2022MR',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Meja rapat besar',
                'user_assigned' => 'Ruang Rapat',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 18000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Rak Buku Perpustakaan',
                'room_name' => 'Perpustakaan',
                'location' => 'Gedung B',
                'floor' => 'Lantai 2',
                'asset_code' => 'AKT-022',
                'unit_code' => 'SAT-022',
                'received_date' => '2021-07-10',
                'purchase_price' => 12000000,
                'useful_life' => 15,
                'salvage_value' => 2000000,
                'type' => 'Furniture',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 7.0,
                'brand' => 'Futura',
                'serial_number' => 'FT2021RBK',
                'quantity' => 20,
                'status' => 'Baik',
                'description' => 'Rak penyimpanan buku',
                'user_assigned' => 'Perpustakaan',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 12000000,
                'last_depreciation_date' => null,
            ],

            // PERALATAN LABORATORIUM
            [
                'name' => 'Mikroskop Digital Olympus',
                'room_name' => 'Lab Biologi',
                'location' => 'Gedung Lab',
                'floor' => 'Lantai 2',
                'asset_code' => 'AKT-023',
                'unit_code' => 'SAT-023',
                'received_date' => '2023-06-01',
                'purchase_price' => 55000000,
                'useful_life' => 10,
                'salvage_value' => 8000000,
                'type' => 'Peralatan Lab',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Olympus',
                'serial_number' => 'OL2023MKR',
                'quantity' => 3,
                'status' => 'Baik',
                'description' => 'Mikroskop untuk praktikum',
                'user_assigned' => 'Lab Biologi',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 55000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Autoclave Sterilizer',
                'room_name' => 'Lab Kimia',
                'location' => 'Gedung Lab',
                'floor' => 'Lantai 3',
                'asset_code' => 'AKT-024',
                'unit_code' => 'SAT-024',
                'received_date' => '2022-09-15',
                'purchase_price' => 35000000,
                'useful_life' => 8,
                'salvage_value' => 5000000,
                'type' => 'Peralatan Lab',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 14.0,
                'brand' => 'Hirayama',
                'serial_number' => 'HR2022ATC',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Autoclave untuk sterilisasi',
                'user_assigned' => 'Lab Kimia',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 35000000,
                'last_depreciation_date' => null,
            ],

            // KENDARAAN TAMBAHAN
            [
                'name' => 'Bus Pariwisata Hino',
                'room_name' => 'Parkir Bus',
                'location' => 'Area Parkir',
                'floor' => 'Ground',
                'asset_code' => 'AKT-025',
                'unit_code' => 'SAT-025',
                'received_date' => '2020-08-20',
                'purchase_price' => 650000000,
                'useful_life' => 10,
                'salvage_value' => 100000000,
                'type' => 'Kendaraan',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 20.0,
                'brand' => 'Hino',
                'serial_number' => 'HN2020BUS',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Bus untuk kegiatan kampus',
                'user_assigned' => 'Pool Kendaraan',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 650000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Ambulance Toyota Hiace',
                'room_name' => 'Parkir Klinik',
                'location' => 'Gedung Klinik',
                'floor' => 'Ground',
                'asset_code' => 'AKT-026',
                'unit_code' => 'SAT-026',
                'received_date' => '2023-03-10',
                'purchase_price' => 450000000,
                'useful_life' => 8,
                'salvage_value' => 80000000,
                'type' => 'Kendaraan',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Toyota',
                'serial_number' => 'TY2023AMB',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Ambulance klinik kampus',
                'user_assigned' => 'Klinik Kampus',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 450000000,
                'last_depreciation_date' => null,
            ],

            // ASET LAINNYA
            [
                'name' => 'Generator Listrik 50 KVA',
                'room_name' => 'Ruang Genset',
                'location' => 'Gedung A',
                'floor' => 'Basement',
                'asset_code' => 'AKT-027',
                'unit_code' => 'SAT-027',
                'received_date' => '2021-12-05',
                'purchase_price' => 85000000,
                'useful_life' => 12,
                'salvage_value' => 15000000,
                'type' => 'Mesin',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Perkins',
                'serial_number' => 'PK2021GEN',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Generator cadangan listrik',
                'user_assigned' => 'Teknik Gedung',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 85000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Sound System TOA Conference',
                'room_name' => 'Aula Utama',
                'location' => 'Gedung B',
                'floor' => 'Lantai 1',
                'asset_code' => 'AKT-028',
                'unit_code' => 'SAT-028',
                'received_date' => '2022-07-20',
                'purchase_price' => 65000000,
                'useful_life' => 8,
                'salvage_value' => 10000000,
                'type' => 'Elektronik',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 15.0,
                'brand' => 'TOA',
                'serial_number' => 'TOA2022SND',
                'quantity' => 1,
                'status' => 'Baik',
                'description' => 'Sound system aula',
                'user_assigned' => 'Aula',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 65000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Lift Penumpang Mitsubishi',
                'room_name' => 'Shaft Lift',
                'location' => 'Gedung A',
                'floor' => '1-5',
                'asset_code' => 'AKT-029',
                'unit_code' => 'SAT-029',
                'received_date' => '2019-05-15',
                'purchase_price' => 450000000,
                'useful_life' => 20,
                'salvage_value' => 50000000,
                'type' => 'Mesin',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => null,
                'brand' => 'Mitsubishi',
                'serial_number' => 'MB2019LFT',
                'quantity' => 2,
                'status' => 'Baik',
                'description' => 'Lift gedung utama',
                'user_assigned' => 'Gedung Management',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 450000000,
                'last_depreciation_date' => null,
            ],
            [
                'name' => 'Water Heater Solar Panel',
                'room_name' => 'Rooftop',
                'location' => 'Gedung B',
                'floor' => 'Atap',
                'asset_code' => 'AKT-030',
                'unit_code' => 'SAT-030',
                'received_date' => '2023-08-10',
                'purchase_price' => 38000000,
                'useful_life' => 15,
                'salvage_value' => 5000000,
                'type' => 'Peralatan',
                'depreciation_type' => 'depreciation',
                'custom_depreciation_rate' => 10.0,
                'brand' => 'Solahart',
                'serial_number' => 'SL2023WTR',
                'quantity' => 4,
                'status' => 'Baik',
                'description' => 'Pemanas air tenaga surya',
                'user_assigned' => 'Maintenance',
                'inventory_status' => 'Tercatat',
                'current_book_value' => 38000000,
                'last_depreciation_date' => null,
            ],
        ];

        foreach ($assets as $assetData) {
            Asset::create($assetData);
        }

        $this->command->info('✅ Berhasil membuat 30 dummy data aset!');
    }
}
